package bitcamp.myapp;

// 코드 본문에서 사용할 클래스가 어떤 패키지의 클래스인지 지정한다.
// This Java source file was generated by the Gradle 'init' task

  public class App {
    public static void main(String[] args) {
      System.out.println("동물병원 보호자 목록");
      System.out.println("----------------------------------");
      
      System.out.print("보호자 ID: ");
      System.out.println(100);
      
      System.out.print("환자 ID: ");
      System.out.println(100);

      System.out.printf("환자명: %s", "강하루");
      System.out.println();
  
      System.out.printf("품종: %s");
      System.out.println();

      System.out.println("나이: " + 20);
      
      System.out.printf("주소: %s");
      System.out.println();

      System.out.printf("연락처: %d");
  
      System.out.printf("성별(남자(M), 여자(W)): %c\n", 'M');
  
    }
  }