package bitcamp.myapp;

// 코드 본문에서 사용할 클래스가 어떤 패키지의 클래스인지 지정한다.
// This Java source file was generated by the Gradle 'init' task

public class App {
  public String getGreeting() {
    return "Hello Woreld!";
  }
  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
  }
}
